### PR TITLE
Add and build git assignment

### PR DESCRIPTION
**Pull request by avahoffman**
Adding an assignment related to git. I thought it would be nice to have them watch something really high level, and save something more detailed for in-class.

### CODE REVIEW

**Comment by avahoffman** [comment]
Could alternatively have them review Jenny Bryan's paper: https://peerj.com/preprints/3159v2/

**Comment by carriewright11** [comment]
> Adding an assignment related to git. I thought it would be nice to have them watch something really high level, and save something more detailed for in-class.

Sounds like a good plan to me!

**Comment by carriewright11** [comment]
Looks great! Maybe we can add the paper as an extra resource and add a line in the assignment saying that if you have never used git or want extra help that you would also recommend reading it?

**Comment by carriewright11** [comment]
Looks good to me!
We could also add these to the resource page... there is already a table for Git/GitHub resources

**Comment by avahoffman** [comment]
Definitely - thanks!

**Pull request merged**
